### ISSUE TITLE
原版书长什么样呢？

### ISSUE THREAD

**Issue by drodata** [zhyoulun/yii2-cookbook-chinese#1]
原版是这个吗？https://www.packtpub.com/web-development/yii2-application-development-cookbook-third-edition

我看了一下你翻译的目录结构，应该不是 https://github.com/samdark/yii2-cookbook 这一本。

翻译辛苦，赞一个 👍

**Comment by allenzhang61** [comment]
原版书的地址是：https://www.packtpub.com/web-development/yii2-application-development-cookbook-third-edition

美亚的地址是：https://www.amazon.com/Yii-Application-Development-Cookbook-Third/dp/1785281763/ref=sr_1_2?ie=UTF8&qid=1498641716&sr=8-2&keywords=yii
